name: Run 80 Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run_nuclear_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: binary by @bgmi
        run: chmod +x bgmi
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot pymongo aiohttp psutil

      - name: Run Danger.py
        run: python3 Danger.py
